
title: Zehao Jin
page-top-title: Zehao Jin (金泽昊)
top-section-bg-text: Bridging AI and Neuroscience 
home-subtitle: Zehao Jin&ensp;|&ensp;金泽昊
copyright-text: '&copy; Zehao Jin 2026. All Rights Reserved.'
